// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gwuud/my-first-crd/pkg/apis/mygroup.example.com/v1alpha1"
	scheme "github.com/gwuud/my-first-crd/pkg/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MyResourceSpecsGetter has a method to return a MyResourceSpecInterface.
// A group's client should implement this interface.
type MyResourceSpecsGetter interface {
	MyResourceSpecs(namespace string) MyResourceSpecInterface
}

// MyResourceSpecInterface has methods to work with MyResourceSpec resources.
type MyResourceSpecInterface interface {
	Create(ctx context.Context, myResourceSpec *v1alpha1.MyResourceSpec, opts v1.CreateOptions) (*v1alpha1.MyResourceSpec, error)
	Update(ctx context.Context, myResourceSpec *v1alpha1.MyResourceSpec, opts v1.UpdateOptions) (*v1alpha1.MyResourceSpec, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MyResourceSpec, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MyResourceSpecList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MyResourceSpec, err error)
	MyResourceSpecExpansion
}

// myResourceSpecs implements MyResourceSpecInterface
type myResourceSpecs struct {
	client rest.Interface
	ns     string
}

// newMyResourceSpecs returns a MyResourceSpecs
func newMyResourceSpecs(c *MygroupV1alpha1Client, namespace string) *myResourceSpecs {
	return &myResourceSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myResourceSpec, and returns the corresponding myResourceSpec object, and an error if there is any.
func (c *myResourceSpecs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MyResourceSpec, err error) {
	result = &v1alpha1.MyResourceSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("myresourcespecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MyResourceSpecs that match those selectors.
func (c *myResourceSpecs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MyResourceSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MyResourceSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("myresourcespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested myResourceSpecs.
func (c *myResourceSpecs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("myresourcespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a myResourceSpec and creates it.  Returns the server's representation of the myResourceSpec, and an error, if there is any.
func (c *myResourceSpecs) Create(ctx context.Context, myResourceSpec *v1alpha1.MyResourceSpec, opts v1.CreateOptions) (result *v1alpha1.MyResourceSpec, err error) {
	result = &v1alpha1.MyResourceSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("myresourcespecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myResourceSpec).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a myResourceSpec and updates it. Returns the server's representation of the myResourceSpec, and an error, if there is any.
func (c *myResourceSpecs) Update(ctx context.Context, myResourceSpec *v1alpha1.MyResourceSpec, opts v1.UpdateOptions) (result *v1alpha1.MyResourceSpec, err error) {
	result = &v1alpha1.MyResourceSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("myresourcespecs").
		Name(myResourceSpec.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myResourceSpec).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the myResourceSpec and deletes it. Returns an error if one occurs.
func (c *myResourceSpecs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("myresourcespecs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *myResourceSpecs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("myresourcespecs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched myResourceSpec.
func (c *myResourceSpecs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MyResourceSpec, err error) {
	result = &v1alpha1.MyResourceSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("myresourcespecs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
