// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gwuud/my-first-crd/pkg/apis/mygroup.example.com/v1alpha1"
	scheme "github.com/gwuud/my-first-crd/pkg/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MyResourceListsGetter has a method to return a MyResourceListInterface.
// A group's client should implement this interface.
type MyResourceListsGetter interface {
	MyResourceLists(namespace string) MyResourceListInterface
}

// MyResourceListInterface has methods to work with MyResourceList resources.
type MyResourceListInterface interface {
	Create(ctx context.Context, myResourceList *v1alpha1.MyResourceList, opts v1.CreateOptions) (*v1alpha1.MyResourceList, error)
	Update(ctx context.Context, myResourceList *v1alpha1.MyResourceList, opts v1.UpdateOptions) (*v1alpha1.MyResourceList, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MyResourceList, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MyResourceListList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MyResourceList, err error)
	MyResourceListExpansion
}

// myResourceLists implements MyResourceListInterface
type myResourceLists struct {
	client rest.Interface
	ns     string
}

// newMyResourceLists returns a MyResourceLists
func newMyResourceLists(c *MygroupV1alpha1Client, namespace string) *myResourceLists {
	return &myResourceLists{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the myResourceList, and returns the corresponding myResourceList object, and an error if there is any.
func (c *myResourceLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MyResourceList, err error) {
	result = &v1alpha1.MyResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("myresourcelists").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MyResourceLists that match those selectors.
func (c *myResourceLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MyResourceListList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MyResourceListList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("myresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested myResourceLists.
func (c *myResourceLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("myresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a myResourceList and creates it.  Returns the server's representation of the myResourceList, and an error, if there is any.
func (c *myResourceLists) Create(ctx context.Context, myResourceList *v1alpha1.MyResourceList, opts v1.CreateOptions) (result *v1alpha1.MyResourceList, err error) {
	result = &v1alpha1.MyResourceList{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("myresourcelists").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myResourceList).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a myResourceList and updates it. Returns the server's representation of the myResourceList, and an error, if there is any.
func (c *myResourceLists) Update(ctx context.Context, myResourceList *v1alpha1.MyResourceList, opts v1.UpdateOptions) (result *v1alpha1.MyResourceList, err error) {
	result = &v1alpha1.MyResourceList{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("myresourcelists").
		Name(myResourceList.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(myResourceList).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the myResourceList and deletes it. Returns an error if one occurs.
func (c *myResourceLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("myresourcelists").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *myResourceLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("myresourcelists").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched myResourceList.
func (c *myResourceLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MyResourceList, err error) {
	result = &v1alpha1.MyResourceList{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("myresourcelists").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
