// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gwuud/my-first-crd/pkg/clientset/clientset/typed/mygroup.example.com/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeMygroupV1alpha1 struct {
	*testing.Fake
}

func (c *FakeMygroupV1alpha1) MyResources(namespace string) v1alpha1.MyResourceInterface {
	return &FakeMyResources{c, namespace}
}

func (c *FakeMygroupV1alpha1) MyResourceLists(namespace string) v1alpha1.MyResourceListInterface {
	return &FakeMyResourceLists{c, namespace}
}

func (c *FakeMygroupV1alpha1) MyResourceSpecs(namespace string) v1alpha1.MyResourceSpecInterface {
	return &FakeMyResourceSpecs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeMygroupV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
